### ISSUE TITLE
Result4k Kotest Matchers

### ISSUE THREAD

**Issue by MrBergin** [fork-handles/forkhandles#12]
Hello there. I've recently decided to migrate one of my projects from Arrow to Result4k as all I really need is a `Result` type. The one thing I miss though are Kotest matchers like `shouldBeInvalid`, `shouldBeValid`, `shouldBeLeft` etc. and I couldn't find anything out of the box for Result4k!

Would this project be interested in a Kotest module? I've made a draft one [here](https://github.com/MrBergin/forkhandles/tree/result4k-kotest-matchers/result4k/kotest) under the Result4k folder which provides various `shouldBeSuccess` and `shouldBeFailure` functions, usage looks like:

```kotlin
fun exampleDivideByZero() {
    val result = divide(5, 0) //function that returns Failure upon divide by zero

    //all of these would pass
    result.shouldBeFailure()
    result shouldBeFailure DivideByZeroFailure
    result shouldBeFailure { reason ->
        reason shouldBe DivideByZeroFailure
    }

    //but this will fail with the appropriate message
    result shouldBeSuccess 5 //Throws AssertionError like: Failure(DivideByZero) should be Success(5)
}
```

If you'd rather keep stuff like this out of this repo I'd be happy to just maintain this in a separate repo as it's pretty small in scope 😅

**Comment by daviddenton** [comment]
Hey. Thanks for raising it. TBH  I think we'd probably rather keep extension modules outside of the main BOM at the moment. But please let us know where the artifact ends up and we'll link to it from the result4k README so people can find it. 🙃

**Comment by MrBergin** [comment]
Ah I thought that might be the case! Will keep you posted.

**Comment by MrBergin** [comment]
Not getting as much time as I'd like to play around with this. Have a repo here: https://github.com/MrBergin/result4k-kotest-matchers. I need to look into the publishing side of things as I'm not terrible familiar with it.

**Comment by daviddenton** [comment]
no problem (or rush) - just let us know when you're happy and we'll stick a link on. 😄

**Comment by MrBergin** [comment]
Hey, I've pushed up a pre-release version 0.0.1 here https://search.maven.org/artifact/dev.mrbergin/result4k-kotest-matchers. 

It's only a handful of functions but I'd like to use this myself a bit more before I'd move it to first major release just to be safe :)

**Comment by daviddenton** [comment]
Excellent! Just let us know when you're ready and we'll add a link to the README 😄

**Comment by MrBergin** [comment]
Hi David, finally got some spare time! I'm ready now, and have added a new release which is up to date with forkhandles' latest version.

If there's anything lacking in it I need to address or any input you want to give it would greatly appreciated, but otherwise I'm pretty happy with it.

Linking again for convenience: https://github.com/MrBergin/result4k-kotest-matchers

**Comment by daviddenton** [comment]
Cool. We'll put it into the readme. :)
