### ISSUE TITLE
[fabrikate4k] Nullable properties are randomly set to null

### ISSUE THREAD

**Issue by huanlui** [fork-handles/forkhandles#23]
**Current status**

Nullable properties are randomly set to null using the config `Random`:

```
 fun makeRandomInstance(classRef: KClass<*>, type: KType): Any? =
        when {
            type.isMarkedNullable && config.random.nextBoolean() -> null
````

**Proposed change**

Allow to make this configurable:

- Current behaviour (default): randomly set to null.
- Always set to null.
- Never set to null.

**Comment by daviddenton** [comment]
👍
