### ISSUE TITLE
[fabrikate4k] Add boolean Fabricator

### ISSUE THREAD

**Issue by rbraeunlich** [fork-handles/forkhandles#26]
Hi everyone,
I was stumbling upon this when trying to create a supposely simple data class. There is a Fabricator instance for every primitive type exception boolean in the library. Is it intentional that there is none for boolean? Adding something like
```
class BooleanFabricator(private val random: Random = Random) : Fabricator<Boolean> {
    override fun invoke() = random.nextBoolean()
}
```
should be easy enough. Therefore I wonder is this was intentionally omitted.
Cheers,
Ronny

**Comment by daviddenton** [comment]
Nope - total oversight. will add it /facepalm :)

**Comment by rbraeunlich** [comment]
No problem ^^
While you're at it you might wanna add a ByteFabricator, too. There is only one for ByteArray.
