### ISSUE TITLE
running into NoUsableConstructor after update

### ISSUE THREAD

**Issue by Groath** [fork-handles/forkhandles#36]
Hey there,

I've updated from 2.2.0.0 to 2.3.0.0 and am running into the exception `dev.forkhandles.fabrikate.InstanceFabricator$NoUsableConstructor` when trying to use `Fabrikate().random<XXX>()` on any self-written class in the whole project. Are there any changes I need to make to the code after updating the version? What could be the causes if nothing changed codewise? Also what info do you need from me to tackle this?

Thanks!

**Comment by daviddenton** [comment]
The only real change between 2.2.0.0 and 2.3.0.0 was the upgrade to Kotlin 1.7.20. Can you confirm that you're on the latest Kotlin?

**Comment by Groath** [comment]
Guess that could be the problem. Can't check right now because I'm on vacation but I'll close the issue and get back if running the latest Kotlin did not solve the issue. Thanks!
